export const ErrorCodes = {
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  STORY_NOT_FOUND: 'STORY_NOT_FOUND',
  STORY_EXPIRED: 'STORY_EXPIRED',
  FRIEND_ALREADY_EXISTS: 'FRIEND_ALREADY_EXISTS',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_MEDIA_TYPE: 'INVALID_MEDIA_TYPE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export type ErrorCodeType = typeof ErrorCodes[keyof typeof ErrorCodes];
