import jwt from 'jsonwebtoken';
import { env } from '../config/env';
import { AuthenticationError } from '../middleware/error';

export interface AuthUser {
  id: string;
  email: string;
  auth0Id?: string;
}

export interface IAuthProvider {
  verifyToken(token: string): Promise<AuthUser>;
  generateToken(user: { id: string; email: string }): string;
}

export class JWTAuthProvider implements IAuthProvider {
  async verifyToken(token: string): Promise<AuthUser> {
    try {
      const decoded = jwt.verify(token, env.JWT_SECRET) as { id: string; email: string };
      return {
        id: decoded.id,
        email: decoded.email
      };
    } catch (err) {
      throw new AuthenticationError('Invalid local JWT signature.');
    }
  }

  generateToken(user: { id: string; email: string }): string {
    return jwt.sign(
      { id: user.id, email: user.email },
      env.JWT_SECRET,
      { expiresIn: env.JWT_EXPIRES_IN as any }
    );
  }
}

export class Auth0Provider implements IAuthProvider {
  async verifyToken(token: string): Promise<AuthUser> {
    try {
      const decoded = jwt.decode(token) as { sub: string; email?: string } | null;
      if (!decoded || !decoded.sub) {
        throw new AuthenticationError('Malformed Auth0 token structure.');
      }
      return {
        id: decoded.sub,
        email: decoded.email || '',
        auth0Id: decoded.sub
      };
    } catch (err: any) {
      throw new AuthenticationError(`Auth0 token verification failed: ${err.message}`);
    }
  }

  generateToken(user: { id: string; email: string }): string {
    // In Auth0, tokens are generated by Auth0 service provider, not locally
    return '';
  }
}

export function getAuthProvider(): IAuthProvider {
  if (env.AUTH_PROVIDER === 'auth0') {
    return new Auth0Provider();
  }
  return new JWTAuthProvider();
}
